spring:
  application:
    name: SkyWatch
  datasource:
    url: jdbc:postgresql://localhost:5433/skywatch
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
geonames:
  username: semyon610
  style: SHORT
telegram:
  bot:
    url: https://api.telegram.org/bot
    token: ${TELEGRAM_BOT_TOKEN}
    auth-url: ${telegram.bot.url}${telegram.bot.token}


