spring:
  application:
    name: SkyWatch
  datasource:
    url: jdbc:postgresql://localhost:5433/skywatch
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
  liquibase:
    enabled: true
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
app:
  geonames:
    username: ${GEONAMES_USERNAME}
    style: FULL
    inside-boundary: TRUE
    geo-name-source: cities500
    max-rows: 1
  location:
    search-radius-meters: 5000