[versions]
spring-boot = "4.1.1"
dependency-management = "1.1.7"
lombok = "1.18.46"
java = "17"
junit = "6.1.3"

[libraries]
#Spring Boot
spring-boot-devtools = { group = "org.springframework.boot", name = "spring-boot-devtools", version.ref = "spring-boot" }
spring-boot-starter = { group = "org.springframework.boot", name = "spring-boot-starter", version.ref = "spring-boot" }
spring-boot-starter-test = { group = "org.springframework.boot", name = "spring-boot-starter-test", version.ref = "spring-boot" }
spring-boot-configuration-processor = { group = "org.springframework.boot", name = "spring-boot-configuration-processor", version.ref = "spring-boot" }

#Lombok
projectlombok = { group = "org.projectlombok", name = "lombok", version.ref = "lombok" }

#JUnit
junit = { group = "org.junit", name = "junit-bom", version.ref = "junit" }
junit-platform-launcher = { group = "org.junit.platform", name = "junit-platform-launcher", version.ref = "junit" }

[plugins]
dependency-management = { id = "io.spring.dependency-management", version.ref = "dependency-management" }
spring-boot = { id = "org.springframework.boot", version.ref = "spring-boot" }